# AULA 4. 21-10 (PARTE 2)

## BIBLIOTECA NUMPY

In [1]:
list_2D = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]
print(list_2D[1][2])

6


In [11]:
#!pip numpy
import numpy as np

arr1 = numpy.array([1,2,3])
arr2 = np.array([1,2,3])

print(arr1)
print(arr2)

print()
lst1 = [1,2,3]
print(lst1) #lista tem vírgula

print()
arr3 = np.array(lst1)
print(arr3) #array não tem vírgula

print()
print(type(lst1))
print(type(arr3))

[1 2 3]
[1 2 3]

[1, 2, 3]

[1 2 3]

<class 'list'>
<class 'numpy.ndarray'>


In [16]:

arr5 = np.array([1,2,3])
print(arr5)
arr6 = np.arange(5)
print(arr6)
arr7 = np.zeros(5)
print(arr7)
arr8 = np.ones(5)
print(arr8)
arr9 = np.linspace(1,5,10)
print(arr9)
arr10 = np.zeros((3,7)) #3 linhas e 7 colunas
print(arr10)
arr11 = np.eye(3) 
print(arr11)
arr12 = np.full((3,7),9) 
print(arr12)

[1 2 3]
[0 1 2 3 4]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]
